import subprocess
import os
import shutil
import json
import sys

# Ensure stdout/stderr use UTF-8 encoding on Windows
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")


def update_obsidian_canvas():
    canvas_path = "Project Dashboard.canvas"
    api_docs_dir = "docs/api"
    
    # If the canvas doesn't exist yet, initialize an empty one
    if not os.path.exists(canvas_path):
        canvas_data = {"nodes": [], "edges": []}
    else:
        with open(canvas_path, "r", encoding="utf-8") as f:
            canvas_data = json.load(f)

    # Filter out existing API doc cards to prevent infinite duplicates
    canvas_data["nodes"] = [n for n in canvas_data.get("nodes", []) if "api/" not in n.get("file", "")]

    # Find all Markdown files generated by Sphinx
    if not os.path.exists(api_docs_dir):
        print("⚠️ API docs directory not found. Run documentation generator first.")
        return

    md_files = [f for f in os.listdir(api_docs_dir) if f.endswith(".md")]
    
    # Grid Layout Math Configurations
    start_x, start_y = 0, 0
    card_width, card_height = 400, 500
    padding_x, padding_y = 50, 50
    columns = 3

    for index, file_name in enumerate(sorted(md_files)):
        col = index % columns
        row = index // columns
        
        # Calculate distinct grid locations for every API file node
        pos_x = start_x + (col * (card_width + padding_x))
        pos_y = start_y + (row * (card_height + padding_y))
        
        # Build node structure using internal obsidian relative paths
        node_id = f"api_node_{index}"
        node_file_path = f"docs/api/{file_name}"
        
        new_node = {
            "id": node_id,
            "type": "file",
            "file": node_file_path,
            "x": pos_x,
            "y": pos_y,
            "width": card_width,
            "height": card_height
        }
        canvas_data["nodes"].append(new_node)

    # Save changes directly back into the vault canvas layout
    with open(canvas_path, "w", encoding="utf-8") as f:
        json.dump(canvas_data, f, indent=2)
        
    print(f"🎨 Embedded {len(md_files)} documentation pages into '{canvas_path}' layout grid.")


def generate_python_docs():
    src_dir = os.path.abspath("app")
    docs_source_dir = os.path.abspath("docs/source")
    output_dir = os.path.abspath("docs/api")

    os.makedirs(docs_source_dir, exist_ok=True)

    print("🔄 Step 1: Scanning source code for layout mapping...")
    # Run sphinx.ext.apidoc via the python executable
    subprocess.run([
        sys.executable, "-m", "sphinx.ext.apidoc", "-o", docs_source_dir, src_dir, "-f", "--separate"
    ], check=True)

    print("🔄 Step 2: Converting code docstrings into Obsidian Markdown...")
    # Run sphinx-build module via python executable
    subprocess.run([
        sys.executable, "-m", "sphinx", "-b", "markdown", docs_source_dir, output_dir
    ], check=True)


    print("✅ Success! API documentation generated inside /docs/api/")

if __name__ == "__main__":
    generate_python_docs()
    update_obsidian_canvas()
